// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by hand to satisfy runtime.Object (no controller-gen in this
// PoC module). Keep in sync with nodeprofile_types.go.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto copies the receiver into out.
func (in *AppCDSSpec) DeepCopyInto(out *AppCDSSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *AppCDSSpec) DeepCopy() *AppCDSSpec {
	if in == nil {
		return nil
	}
	out := new(AppCDSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *JDKRef) DeepCopyInto(out *JDKRef) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *JDKRef) DeepCopy() *JDKRef {
	if in == nil {
		return nil
	}
	out := new(JDKRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *JDKSource) DeepCopyInto(out *JDKSource) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *JDKSource) DeepCopy() *JDKSource {
	if in == nil {
		return nil
	}
	out := new(JDKSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *LauncherRef) DeepCopyInto(out *LauncherRef) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *LauncherRef) DeepCopy() *LauncherRef {
	if in == nil {
		return nil
	}
	out := new(LauncherRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *LauncherSource) DeepCopyInto(out *LauncherSource) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *LauncherSource) DeepCopy() *LauncherSource {
	if in == nil {
		return nil
	}
	out := new(LauncherSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NodePoolRef) DeepCopyInto(out *NodePoolRef) {
	*out = *in
	if in.Names != nil {
		out.Names = make([]string, len(in.Names))
		copy(out.Names, in.Names)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NodePoolRef) DeepCopy() *NodePoolRef {
	if in == nil {
		return nil
	}
	out := new(NodePoolRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *RegistrySpec) DeepCopyInto(out *RegistrySpec) {
	*out = *in
	if in.Mirrors != nil {
		out.Mirrors = make(map[string]string, len(in.Mirrors))
		for k, v := range in.Mirrors {
			out.Mirrors[k] = v
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *RegistrySpec) DeepCopy() *RegistrySpec {
	if in == nil {
		return nil
	}
	out := new(RegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *RolloutSpec) DeepCopyInto(out *RolloutSpec) {
	*out = *in
	if in.MaxUnavailable != nil {
		out.MaxUnavailable = new(intstr.IntOrString)
		*out.MaxUnavailable = *in.MaxUnavailable
	}
	if in.Validate != nil {
		out.Validate = new(bool)
		*out.Validate = *in.Validate
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *RolloutSpec) DeepCopy() *RolloutSpec {
	if in == nil {
		return nil
	}
	out := new(RolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NodeProfileSpec) DeepCopyInto(out *NodeProfileSpec) {
	*out = *in
	in.NodePool.DeepCopyInto(&out.NodePool)
	if in.JDKs != nil {
		out.JDKs = make([]JDKRef, len(in.JDKs))
		for i := range in.JDKs {
			in.JDKs[i].DeepCopyInto(&out.JDKs[i])
		}
	}
	if in.Launchers != nil {
		out.Launchers = make([]LauncherRef, len(in.Launchers))
		copy(out.Launchers, in.Launchers)
	}
	if in.AppCDS != nil {
		out.AppCDS = in.AppCDS.DeepCopy()
	}
	if in.Registry != nil {
		out.Registry = in.Registry.DeepCopy()
	}
	in.Rollout.DeepCopyInto(&out.Rollout)
}

// DeepCopy returns a deep copy of the receiver.
func (in *NodeProfileSpec) DeepCopy() *NodeProfileSpec {
	if in == nil {
		return nil
	}
	out := new(NodeProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NodeProfileStatus) DeepCopyInto(out *NodeProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NodeProfileStatus) DeepCopy() *NodeProfileStatus {
	if in == nil {
		return nil
	}
	out := new(NodeProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NodeProfile) DeepCopyInto(out *NodeProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *NodeProfile) DeepCopy() *NodeProfile {
	if in == nil {
		return nil
	}
	out := new(NodeProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *NodeProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *NodeProfileList) DeepCopyInto(out *NodeProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NodeProfile, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NodeProfileList) DeepCopy() *NodeProfileList {
	if in == nil {
		return nil
	}
	out := new(NodeProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *NodeProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
