// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package sh.brewlet.maven.plugin;

import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import sh.brewlet.maven.plugin.model.JvmConfig;
import sh.brewlet.maven.plugin.model.Port;
import sh.brewlet.maven.plugin.util.FrameworkDetector;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

/**
 * <strong>brewlet:manifest</strong> — Emit a {@code JavaApplication} custom
 * resource YAML (or a raw Kubernetes {@code Deployment}) to
 * {@code target/brewlet/} so developers can apply it with
 * {@code kubectl apply -f target/brewlet/javaapplication.yaml}.
 *
 * <p>The generated CR uses the JavaApplication schema and examples maintained in
 * https://github.com/microsoft/brewlet/tree/main/kubernetes.
 *
 * <p>Example:
 * <pre>
 * mvn brewlet:manifest
 * kubectl apply -f target/brewlet/javaapplication.yaml
 * </pre>
 */
@Mojo(name = "manifest",
      requiresProject = true,
      threadSafe = true)
public class ManifestMojo extends AbstractBrewletMojo {

    /**
     * Kubernetes namespace for the generated manifest.
     * Defaults to {@code default}.
     */
    @Parameter(property = "brewlet.namespace", defaultValue = "default")
    private String namespace;

    /**
     * Application name for the {@code JavaApplication} resource.
     * Defaults to {@code ${project.artifactId}}.
     */
    @Parameter(property = "brewlet.appName", defaultValue = "${project.artifactId}")
    private String appName;

    /**
     * Number of replicas. Defaults to {@code 1}.
     */
    @Parameter(property = "brewlet.replicas", defaultValue = "1")
    private int replicas;

    /**
     * Deployment-side JVM tuning written to the descriptor's {@code jvm.args}
     * (heap, GC, container flags, agents, …). This is a DEPLOYMENT concern and
     * is intentionally separate from the artifact's app-intrinsic launch knobs
     * (enablePreview/addOpens/addExports/addModules/systemProperties). The
     * operator appends these after the artifact flags.
     */
    @Parameter(property = "brewlet.jvmArgs")
    private List<String> jvmArgs;

    /**
     * Container ports the application listens on, written to the descriptor's
     * {@code spec.ports}. This is a DEPLOYMENT concern (Kubernetes Service and
     * probe wiring) and is intentionally not part of the artifact. If empty and
     * the framework is Spring Boot or Quarkus, a default of {@code 8080/http} is
     * used with a warning.
     */
    @Parameter
    private List<Port> ports;

    /**
     * CPU request for the pod. Defaults to {@code "500m"}.
     */
    @Parameter(property = "brewlet.resources.cpuRequest", defaultValue = "500m")
    private String cpuRequest;

    /**
     * Memory request for the pod. Defaults to {@code "256Mi"}.
     */
    @Parameter(property = "brewlet.resources.memoryRequest", defaultValue = "256Mi")
    private String memoryRequest;

    /**
     * CPU limit for the pod. Defaults to {@code "2"}.
     */
    @Parameter(property = "brewlet.resources.cpuLimit", defaultValue = "2")
    private String cpuLimit;

    /**
     * Memory limit for the pod. Defaults to {@code "512Mi"}.
     */
    @Parameter(property = "brewlet.resources.memoryLimit", defaultValue = "512Mi")
    private String memoryLimit;

    @Override
    protected void doExecute() throws MojoExecutionException, MojoFailureException {
        if (image == null || image.isBlank()) {
            throw new MojoExecutionException(
                    "brewlet:manifest requires <image> to be configured.");
        }

        JvmConfig cfg = buildConfig();
        outputDirectory.mkdirs();

        File outputFile = new File(outputDirectory, "javaapplication.yaml");
        try (PrintWriter w = new PrintWriter(new FileWriter(outputFile))) {
            writeJavaApplicationYaml(w, cfg);
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to write JavaApplication manifest", e);
        }

        getLog().info("Brewlet: wrote JavaApplication manifest → " + outputFile.getPath());
        getLog().info("  Apply with: kubectl apply -f " + outputFile.getPath());
    }

    private void writeJavaApplicationYaml(PrintWriter w, JvmConfig cfg) {
        w.println("# Generated by brewlet-maven-plugin " + project.getVersion());
        w.println("# Apply with: kubectl apply -f javaapplication.yaml");
        w.println("---");
        w.println("apiVersion: apps.brewlet.sh/v1alpha1");
        w.println("kind: JavaApplication");
        w.println("metadata:");
        w.println("  name: " + appName);
        w.println("  namespace: " + namespace);
        w.println("  labels:");
        w.println("    app: " + appName);
        w.println("    app.kubernetes.io/name: " + appName);
        w.println("    app.kubernetes.io/version: \"" + project.getVersion() + "\"");
        w.println("    app.kubernetes.io/managed-by: brewlet-maven-plugin");
        w.println("spec:");
        w.println("  artifact:");
        w.println("    image: " + image);
        w.println("    pullPolicy: IfNotPresent");
        w.println("  replicas: " + replicas);
        w.println("  resources:");
        w.println("    requests:");
        w.println("      cpu: \"" + cpuRequest + "\"");
        w.println("      memory: \"" + memoryRequest + "\"");
        w.println("    limits:");
        w.println("      cpu: \"" + cpuLimit + "\"");
        w.println("      memory: \"" + memoryLimit + "\"");
        w.println("  jvm:");
        w.println("    version: " + resolveJdkFeature());
        String resolvedDistribution = resolveJdkDistribution();
        if (resolvedDistribution != null) {
            w.println("    distribution: " + resolvedDistribution);
        }
        String resolvedLauncher = resolveLauncher();
        if (!"java".equals(resolvedLauncher)) {
            w.println("    launcher: " + resolvedLauncher);
        }

        if (jvmArgs != null && !jvmArgs.isEmpty()) {
            w.println("    args:");
            for (String arg : jvmArgs) {
                w.println("      - \"" + arg + "\"");
            }
        }

        if (cfg.getEnv() != null && !cfg.getEnv().isEmpty()) {
            w.println("  env:");
            for (var envVar : cfg.getEnv()) {
                w.println("    - name: " + envVar.getName());
                w.println("      value: \"" + envVar.getValue() + "\"");
            }
        }

        List<Port> resolvedPorts = resolvePorts();
        if (resolvedPorts != null && !resolvedPorts.isEmpty()) {
            w.println("  ports:");
            for (Port p : resolvedPorts) {
                w.println("    - name: " + (p.getName() != null ? p.getName() : "http"));
                w.println("      containerPort: " + p.getContainerPort());
            }
            // Default service and probes for the first port
            Port firstPort = resolvedPorts.get(0);
            w.println("  service:");
            w.println("    enabled: true");
            w.println("    type: ClusterIP");
            w.println("  probes:");
            w.println("    readiness:");
            w.println("      httpGet:");
            w.println("        path: /");
            w.println("        port: " + firstPort.getContainerPort());
            w.println("    liveness:");
            w.println("      httpGet:");
            w.println("        path: /");
            w.println("        port: " + firstPort.getContainerPort());
        }
    }

    /**
     * Resolves the container ports for the descriptor: the configured
     * {@code <ports>} if any, otherwise a framework-inferred default
     * ({@code 8080/http} for Spring Boot / Quarkus) with a warning.
     */
    private List<Port> resolvePorts() {
        if (ports != null && !ports.isEmpty()) {
            return ports;
        }
        FrameworkDetector.Framework framework = FrameworkDetector.detect(project);
        int defaultPort = FrameworkDetector.defaultPort(framework);
        if (defaultPort > 0) {
            getLog().warn("No <ports> configured; using default port " + defaultPort
                    + " for " + framework.label() + " application.");
            return List.of(new Port("http", defaultPort, "TCP"));
        }
        getLog().warn("No <ports> configured. Add <ports><port>"
                + "<name>http</name><containerPort>8080</containerPort></port></ports> "
                + "to the plugin configuration.");
        return null;
    }
}
