// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package sh.brewlet.maven.plugin;

import org.apache.maven.model.Dependency;
import org.apache.maven.project.MavenProject;
import org.junit.jupiter.api.Test;
import sh.brewlet.maven.plugin.model.EnvVar;
import sh.brewlet.maven.plugin.model.JvmConfig;
import sh.brewlet.maven.plugin.model.Port;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.io.Writer;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ManifestMojoTest {
    @Test
    void argumentsAndEnvironmentValuesRoundTripExactly() throws Exception {
        List<String> values = List.of("", "plain", "-Dgreeting=\"hello\"",
                "-Dregex=\\d+\\s*", "line one\nline two\r\n\tindented",
                "caf\u00e9 \u65e5\u672c\u8a9e \ud83c\udf31", "false", "123", "# comment: [mapping]",
                controlsAndUnicodeLineBreaks());
        ManifestMojo mojo = mojo();
        set(mojo, "jvmArgs", values);
        JvmConfig config = new JvmConfig();
        List<EnvVar> env = new ArrayList<>();
        for (int i = 0; i < values.size(); i++) {
            env.add(new EnvVar("VALUE_" + i, values.get(i)));
        }
        config.setEnv(env);

        String yaml = render(mojo, config);
        assertEquals(values, scalars(yaml, "      - "));
        assertEquals(values, scalars(yaml, "      value: "));
        assertFalse(yaml.contains("\u0085"));
        assertFalse(yaml.contains("\u2028"));
        assertFalse(yaml.contains("\u2029"));
        assertTrue(yaml.contains("\ud83c\udf31"));
        assertFalse(yaml.contains("\\ud83c"));
    }

    @Test
    void everyDynamicStringFieldUsesTheSameEncoding() throws Exception {
        String value = "on: \"quoted\"\\path\n\u65e5\u672c\u8a9e \ud83c\udf31\u0085end";
        ManifestMojo mojo = mojo();
        mojo.project.setVersion(value);
        mojo.image = value;
        mojo.jdkDistribution = value;
        mojo.launcher = value;
        for (String field : List.of("appName", "namespace", "cpuRequest", "memoryRequest",
                "cpuLimit", "memoryLimit")) {
            set(mojo, field, value);
        }
        set(mojo, "ports", List.of(new Port(value, 8080, "TCP")));
        JvmConfig config = new JvmConfig();
        config.setEnv(List.of(new EnvVar(value, value)));

        String yaml = render(mojo, config);
        for (String prefix : List.of("  name: ", "  namespace: ", "    app: ",
                "    app.kubernetes.io/name: ", "    app.kubernetes.io/version: ",
                "    image: ", "    distribution: ", "    launcher: ", "      value: ")) {
            assertEquals(List.of(value), scalars(yaml, prefix), prefix);
        }
        assertEquals(List.of(value, value), scalars(yaml, "      cpu: "));
        assertEquals(List.of(value, value), scalars(yaml, "      memory: "));
        assertEquals(List.of(value, value), scalars(yaml, "    - name: "));
        assertEquals(List.of(value), scalars(yaml, "# Generated by brewlet-maven-plugin "));
        assertTrue(yaml.contains("  replicas: 1\n"));
        assertTrue(yaml.contains("    version: 17\n"));
        assertTrue(yaml.contains("      containerPort: 8080\n"));
    }

    @Test
    void yamlScalarEscapesEveryNonPrintableCharacterWithoutLosingUnicode() throws Exception {
        String value = controlsAndUnicodeLineBreaks() + "\u65e5\u672c\u8a9e \ud83c\udf31\ufffe\uffff";
        String scalar = ManifestMojo.yamlString(value);
        assertEquals(value, AbstractBrewletMojo.MAPPER.readValue(scalar, String.class));
        assertTrue(scalar.startsWith("\"") && scalar.endsWith("\""));
        for (char c : scalar.toCharArray()) {
            assertFalse(c < 0x20 || (c >= 0x7f && c <= 0x9f)
                    || c == 0x2028 || c == 0x2029 || c >= 0xfffe);
        }
        assertEquals("\"\"", ManifestMojo.yamlString(""));
    }

    @Test
    void outputFailuresAreReported() throws Exception {
        PrintWriter writer = new PrintWriter(new Writer() {
            @Override
            public void write(char[] buffer, int offset, int length) throws IOException {
                throw new IOException("output unavailable");
            }

            @Override
            public void flush() {}

            @Override
            public void close() {}
        });
        assertThrows(IOException.class, () -> mojo().writeJavaApplicationYaml(writer, new JvmConfig()));
    }

    @Test
    void configuredPortsDoNotInventHttpHealthEndpoints() throws Exception {
        for (Port port : List.of(new Port("http", 8080, "TCP"),
                new Port("grpc", 9090, "TCP"), new Port("metrics", 9100, "TCP"))) {
            ManifestMojo mojo = mojo();
            set(mojo, "ports", List.of(port));

            String yaml = render(mojo, new JvmConfig());

            assertTrue(yaml.contains("      containerPort: " + port.getContainerPort() + "\n"));
            assertTrue(yaml.contains("  service:\n    enabled: true\n"));
            assertNoInferredProbes(yaml);
        }
    }

    @Test
    void inferredFrameworkPortsDoNotInventHttpHealthEndpoints() throws Exception {
        for (String[] coordinates : List.of(
                new String[]{"org.springframework.boot", "spring-boot"},
                new String[]{"io.quarkus", "quarkus-core"})) {
            ManifestMojo mojo = mojo();
            Dependency dependency = new Dependency();
            dependency.setGroupId(coordinates[0]);
            dependency.setArtifactId(coordinates[1]);
            mojo.project.setDependencies(List.of(dependency));

            String yaml = render(mojo, new JvmConfig());

            assertTrue(yaml.contains("      containerPort: 8080\n"));
            assertTrue(yaml.contains("  service:\n    enabled: true\n"));
            assertNoInferredProbes(yaml);
        }
    }

    @Test
    void portlessApplicationsRemainWithoutServiceOrProbes() throws Exception {
        String yaml = render(mojo(), new JvmConfig());
        assertFalse(yaml.contains("  ports:"));
        assertFalse(yaml.contains("  service:"));
        assertNoInferredProbes(yaml);
    }

    private static void assertNoInferredProbes(String yaml) {
        assertFalse(yaml.contains("  probes:"), "ports do not declare a health contract");
        assertFalse(yaml.contains("httpGet:"));
        assertFalse(yaml.contains("liveness:"));
        assertFalse(yaml.contains("readiness:"));
    }

    private static ManifestMojo mojo() throws ReflectiveOperationException {
        ManifestMojo mojo = new ManifestMojo();
        mojo.project = new MavenProject();
        mojo.project.setVersion("1.0");
        mojo.jdkFeature = 17;
        mojo.image = "registry.example.com/app@sha256:" + "1".repeat(64);
        set(mojo, "appName", "orders");
        set(mojo, "namespace", "default");
        set(mojo, "replicas", 1);
        set(mojo, "cpuRequest", "500m");
        set(mojo, "memoryRequest", "256Mi");
        set(mojo, "cpuLimit", "2");
        set(mojo, "memoryLimit", "512Mi");
        return mojo;
    }

    private static void set(ManifestMojo mojo, String name, Object value)
            throws ReflectiveOperationException {
        Field field = ManifestMojo.class.getDeclaredField(name);
        field.setAccessible(true);
        field.set(mojo, value);
    }

    private static String render(ManifestMojo mojo, JvmConfig config) throws IOException {
        StringWriter result = new StringWriter();
        mojo.writeJavaApplicationYaml(new PrintWriter(result), config);
        return result.toString();
    }

    private static List<String> scalars(String yaml, String prefix) throws IOException {
        List<String> values = new ArrayList<>();
        for (String line : yaml.lines().toList()) {
            if (line.startsWith(prefix)) {
                // Emitted scalars use the common JSON/YAML quoted-string grammar.
                values.add(AbstractBrewletMojo.MAPPER.readValue(
                        line.substring(prefix.length()), String.class));
            }
        }
        return values;
    }

    private static String controlsAndUnicodeLineBreaks() {
        StringBuilder value = new StringBuilder();
        for (char c = 0; c < 0x20; c++) {
            value.append(c);
        }
        for (char c = 0x7f; c <= 0x9f; c++) {
            value.append(c);
        }
        return value.append('\u2028').append('\u2029').toString();
    }
}
