// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package sh.brewlet.maven.plugin;

import org.apache.maven.model.Dependency;
import org.apache.maven.project.MavenProject;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import sh.brewlet.maven.plugin.model.EnvVar;
import sh.brewlet.maven.plugin.model.JvmConfig;
import sh.brewlet.maven.plugin.model.Port;
import sh.brewlet.maven.plugin.model.Probe;
import sh.brewlet.maven.plugin.model.Probes;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.io.Writer;
import java.lang.reflect.Field;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ManifestMojoTest {
    @Test
    void manifestJdkComesFromMainCompilerConfiguration() throws Exception {
        ManifestMojo mojo = mojo();
        mojo.jdkFeature = null;
        var compiler = new org.apache.maven.model.Plugin();
        compiler.setArtifactId("maven-compiler-plugin");
        compiler.setConfiguration(org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(
                new java.io.StringReader("<configuration><release>11</release></configuration>")));
        mojo.project.getBuild().addPlugin(compiler);
        assertTrue(render(mojo, new JvmConfig()).contains("    version: 11\n"));
    }

    @Test
    void explicitFeatureWinsAndInvalidExplicitValuesDoNotTriggerInference() throws Exception {
        ManifestMojo mojo = mojo();
        mojo.project.getProperties().setProperty("maven.compiler.release", "${unknown}");
        assertTrue(render(mojo, new JvmConfig()).contains("    version: 17\n"));
        for (int invalid : List.of(0, -1)) {
            mojo.jdkFeature = invalid;
            assertThrows(org.apache.maven.plugin.MojoExecutionException.class, () -> render(mojo, new JvmConfig()));
        }
    }

    @Test
    void argumentsAndEnvironmentValuesRoundTripExactly() throws Exception {
        List<String> values = List.of("", "plain", "-Dgreeting=\"hello\"",
                "-Dregex=\\d+\\s*", "line one\nline two\r\n\tindented",
                "caf\u00e9 \u65e5\u672c\u8a9e \ud83c\udf31", "false", "123", "# comment: [mapping]",
                controlsAndUnicodeLineBreaks());
        ManifestMojo mojo = mojo();
        set(mojo, "jvmArgs", values);
        JvmConfig config = new JvmConfig();
        List<EnvVar> env = new ArrayList<>();
        for (int i = 0; i < values.size(); i++) {
            env.add(new EnvVar("VALUE_" + i, values.get(i)));
        }
        config.setEnv(env);

        String yaml = render(mojo, config);
        assertEquals(values, scalars(yaml, "      - "));
        assertEquals(values, scalars(yaml, "      value: "));
        assertFalse(yaml.contains("\u0085"));
        assertFalse(yaml.contains("\u2028"));
        assertFalse(yaml.contains("\u2029"));
        assertTrue(yaml.contains("\ud83c\udf31"));
        assertFalse(yaml.contains("\\ud83c"));
    }

    @Test
    void everyDynamicStringFieldUsesTheSameEncoding() throws Exception {
        String value = "on: \"quoted\"\\path\n\u65e5\u672c\u8a9e \ud83c\udf31\u0085end";
        ManifestMojo mojo = mojo();
        mojo.project.setVersion(value);
        mojo.jdkDistribution = value;
        mojo.launcher = value;
        for (String field : List.of("appName", "namespace", "cpuRequest", "memoryRequest",
                "cpuLimit", "memoryLimit")) {
            set(mojo, field, value);
        }
        set(mojo, "ports", List.of(new Port(value, 8080, "TCP")));
        JvmConfig config = new JvmConfig();
        config.setEnv(List.of(new EnvVar(value, value)));

        String yaml = render(mojo, config);
        for (String prefix : List.of("  name: ", "  namespace: ", "    app: ",
                "    app.kubernetes.io/name: ", "    app.kubernetes.io/version: ",
                "    distribution: ", "    launcher: ", "      value: ")) {
            assertEquals(List.of(value), scalars(yaml, prefix), prefix);
        }
        assertEquals(List.of(value, value), scalars(yaml, "      cpu: "));
        assertEquals(List.of(value, value), scalars(yaml, "      memory: "));
        assertEquals(List.of(value, value), scalars(yaml, "    - name: "));
        assertEquals(List.of(value), scalars(yaml, "# Generated by brewlet-maven-plugin "));
        assertTrue(yaml.contains("  replicas: 1\n"));
        assertTrue(yaml.contains("    version: 17\n"));
        assertTrue(yaml.contains("      containerPort: 8080\n"));
    }

    @Test
    void yamlScalarEscapesEveryNonPrintableCharacterWithoutLosingUnicode() throws Exception {
        String value = controlsAndUnicodeLineBreaks() + "\u65e5\u672c\u8a9e \ud83c\udf31\ufffe\uffff";
        String scalar = ManifestMojo.yamlString(value);
        assertEquals(value, AbstractBrewletMojo.MAPPER.readValue(scalar, String.class));
        assertTrue(scalar.startsWith("\"") && scalar.endsWith("\""));
        for (char c : scalar.toCharArray()) {
            assertFalse(c < 0x20 || (c >= 0x7f && c <= 0x9f)
                    || c == 0x2028 || c == 0x2029 || c >= 0xfffe);
        }
        assertEquals("\"\"", ManifestMojo.yamlString(""));
    }

    @Test
    void outputFailuresAreReported() throws Exception {
        PrintWriter writer = new PrintWriter(new Writer() {
            @Override
            public void write(char[] buffer, int offset, int length) throws IOException {
                throw new IOException("output unavailable");
            }

            @Override
            public void flush() {}

            @Override
            public void close() {}
        });
        assertThrows(IOException.class, () -> mojo().writeJavaApplicationYaml(writer, new JvmConfig()));
    }

    @Test
    void configuredPortsDoNotInventHttpHealthEndpoints() throws Exception {
        for (Port port : List.of(new Port("http", 8080, "TCP"),
                new Port("grpc", 9090, "TCP"), new Port("metrics", 9100, "TCP"))) {
            ManifestMojo mojo = mojo();
            set(mojo, "ports", List.of(port));

            String yaml = render(mojo, new JvmConfig());

            assertTrue(yaml.contains("      containerPort: " + port.getContainerPort() + "\n"));
            assertTrue(yaml.contains("  service:\n    enabled: true\n"));
            assertNoInferredProbes(yaml);
        }
    }

    @Test
    void inferredFrameworkPortsDoNotInventHttpHealthEndpoints() throws Exception {
        for (String[] coordinates : List.of(
                new String[]{"org.springframework.boot", "spring-boot"},
                new String[]{"io.quarkus", "quarkus-core"})) {
            ManifestMojo mojo = mojo();
            Dependency dependency = new Dependency();
            dependency.setGroupId(coordinates[0]);
            dependency.setArtifactId(coordinates[1]);
            mojo.project.setDependencies(List.of(dependency));

            String yaml = render(mojo, new JvmConfig());

            assertTrue(yaml.contains("      containerPort: 8080\n"));
            assertTrue(yaml.contains("  service:\n    enabled: true\n"));
            assertNoInferredProbes(yaml);
        }
    }

    @Test
    void portlessApplicationsRemainWithoutServiceOrProbes() throws Exception {
        String yaml = render(mojo(), new JvmConfig());
        assertFalse(yaml.contains("  ports:"));
        assertFalse(yaml.contains("  service:"));
        assertNoInferredProbes(yaml);
    }

    @Test
    void httpProbesDefaultToTheFirstPortName() throws Exception {
        ManifestMojo mojo = mojo();
        set(mojo, "ports", List.of(new Port("web", 8080, "TCP"), new Port("admin", 9090, "TCP")));
        Probe readiness = Probe.httpGet("/healthz");
        readiness.setPeriodSeconds(5);
        readiness.setInitialDelaySeconds(0);
        Probe liveness = Probe.httpGet("/livez");
        liveness.setPort("admin");
        liveness.setScheme("https");
        liveness.setFailureThreshold(3);
        set(mojo, "probes", new Probes(readiness, liveness));

        String yaml = render(mojo, new JvmConfig());

        assertTrue(yaml.endsWith("""
                  probes:
                    readiness:
                      httpGet:
                        path: "/healthz"
                        port: "web"
                      initialDelaySeconds: 0
                      periodSeconds: 5
                    liveness:
                      httpGet:
                        path: "/livez"
                        port: "admin"
                        scheme: "HTTPS"
                      failureThreshold: 3
                """), yaml);
    }

    @Test
    void numericTcpAndExecProbesAreRendered() throws Exception {
        ManifestMojo mojo = mojo();
        Probe readiness = new Probe();
        readiness.setPort("8080");
        Probe liveness = new Probe();
        liveness.setCommand(List.of("sh", "-c", "test -f /tmp/alive"));
        liveness.setTimeoutSeconds(2);
        set(mojo, "probes", new Probes(readiness, liveness));

        String yaml = render(mojo, new JvmConfig());

        assertTrue(yaml.endsWith("""
                  probes:
                    readiness:
                      tcpSocket:
                        port: 8080
                    liveness:
                      exec:
                        command:
                          - "sh"
                          - "-c"
                          - "test -f /tmp/alive"
                      timeoutSeconds: 2
                """), yaml);
    }

    @Test
    void pathShorthandsApplyOnlyWhenTheProbeIsNotConfigured() throws Exception {
        ManifestMojo mojo = mojo();
        set(mojo, "ports", List.of(new Port(null, 8080, "TCP")));
        set(mojo, "readinessPath", " /ready ");
        set(mojo, "livenessPath", "/ignored");
        set(mojo, "probes", new Probes(null, Probe.httpGet("/live")));

        String yaml = render(mojo, new JvmConfig());

        assertTrue(yaml.contains("    readiness:\n      httpGet:\n        path: \"/ready\"\n        port: \"http\"\n"), yaml);
        assertTrue(yaml.contains("    liveness:\n      httpGet:\n        path: \"/live\"\n"), yaml);
        assertFalse(yaml.contains("/ignored"));
    }

    @Test
    void invalidProbesFailWithActionableMessages() throws Exception {
        Probe both = Probe.httpGet("/x");
        both.setCommand(List.of("true"));
        Probe relative = Probe.httpGet("healthz");
        Probe unknownName = Probe.httpGet("/x");
        unknownName.setPort("grpc");
        Probe outOfRange = new Probe();
        outOfRange.setPort("70000");
        Probe badScheme = Probe.httpGet("/x");
        badScheme.setScheme("ftp");
        Probe tcpScheme = new Probe();
        tcpScheme.setScheme("HTTPS");
        Probe execPort = new Probe();
        execPort.setCommand(List.of("true"));
        execPort.setPort("http");
        Probe badPeriod = Probe.httpGet("/x");
        badPeriod.setPeriodSeconds(0);

        for (Object[] c : List.of(
                new Object[]{both, "choose one"},
                new Object[]{relative, "must start with '/'"},
                new Object[]{unknownName, "does not match a configured port name (http)"},
                new Object[]{outOfRange, "must be 1-65535"},
                new Object[]{badScheme, "must be HTTP or HTTPS"},
                new Object[]{tcpScheme, "applies only to HTTP probes"},
                new Object[]{execPort, "do not apply"},
                new Object[]{badPeriod, "<periodSeconds> must be >= 1"})) {
            ManifestMojo mojo = mojo();
            set(mojo, "ports", List.of(new Port("http", 8080, "TCP")));
            set(mojo, "probes", new Probes((Probe) c[0], null));
            var e = assertThrows(org.apache.maven.plugin.MojoExecutionException.class,
                    () -> render(mojo, new JvmConfig()));
            assertTrue(e.getMessage().startsWith("<probes><readiness>"), e.getMessage());
            assertTrue(e.getMessage().contains((String) c[1]), e.getMessage());
        }
    }

    @Test
    void networkProbesNeedAPortWhenNoPortsAreConfigured() throws Exception {
        ManifestMojo mojo = mojo();
        set(mojo, "readinessPath", "/healthz");
        var e = assertThrows(org.apache.maven.plugin.MojoExecutionException.class,
                () -> render(mojo, new JvmConfig()));
        assertTrue(e.getMessage().contains("needs a <port>"), e.getMessage());

        Probe numeric = Probe.httpGet("/healthz");
        numeric.setPort("8081");
        set(mojo, "readinessPath", null);
        set(mojo, "probes", new Probes(numeric, null));
        assertTrue(render(mojo, new JvmConfig()).contains("        port: 8081\n"));
    }

    @Test
    void healthModulesAreSuggestedButNeverApplied() throws Exception {
        for (String[] c : List.of(
                new String[]{"org.springframework.boot", "spring-boot-starter-actuator", "/actuator/health/readiness"},
                new String[]{"io.quarkus", "quarkus-smallrye-health", "/q/health/ready"})) {
            ManifestMojo mojo = mojo();
            Dependency dependency = new Dependency();
            dependency.setGroupId(c[0]);
            dependency.setArtifactId(c[1]);
            mojo.project.setDependencies(List.of(dependency));
            set(mojo, "ports", List.of(new Port("http", 8080, "TCP")));
            List<String> warnings = new ArrayList<>();
            mojo.setLog(new org.apache.maven.plugin.logging.SystemStreamLog() {
                @Override
                public void warn(CharSequence content) {
                    warnings.add(content.toString());
                }
            });

            String yaml = render(mojo, new JvmConfig());

            assertNoInferredProbes(yaml);
            assertTrue(warnings.stream().anyMatch(w -> w.contains("-Dbrewlet.readinessPath=" + c[2])), warnings.toString());
        }
    }

    @Test
    void savedPushAndExplicitImageCannotReplaceTheCurrentBuild(@TempDir Path dir) throws Exception {
        ManifestMojo mojo = mojo();
        mojo.outputDirectory = dir.toFile();
        ApplicationBuildResult.clear(mojo.project);
        String override = "other.example.com/app@sha256:" + "2".repeat(64);
        mojo.project.getProperties().setProperty("brewlet.image", override);
        Files.writeString(dir.resolve("push.json"), "{\"deployImage\":\"" + override + "\"}");
        var failure = assertThrows(org.apache.maven.plugin.MojoExecutionException.class,
                mojo::execute);
        assertTrue(failure.getMessage().contains("same Maven invocation"), failure.getMessage());
        assertFalse(Files.exists(dir.resolve("javaapplication.yaml")));
    }

    @Test
    void manifestAlwaysUsesTheCurrentBuildNotPropertiesOrSavedPush(@TempDir Path dir) throws Exception {
        ManifestMojo mojo = mojo();
        mojo.outputDirectory = dir.toFile();
        mojo.project.getProperties().setProperty("brewlet.image", "other.example.com/app:1");
        Files.writeString(dir.resolve("push.json"), "invalid and deliberately ignored");
        mojo.execute();
        String yaml = Files.readString(dir.resolve("javaapplication.yaml"));
        assertTrue(yaml.contains("registry.example.com/app@sha256:" + "1".repeat(64)), yaml);
        assertFalse(yaml.contains("other.example.com"), yaml);
        assertEquals("invalid and deliberately ignored", Files.readString(dir.resolve("push.json")));
    }

    @Test
    void nativeArtifactsAndUnqualifiedLocalImagesAreNotDeployable() throws Exception {
        ManifestMojo mojo = mojo();
        new ApplicationBuildResult("registry.example.com/app:1", "sha256:" + "1".repeat(64),
                "artifact", new JvmConfig()).save(mojo.project);
        assertTrue(assertThrows(org.apache.maven.plugin.MojoExecutionException.class,
                mojo::execute).getMessage().contains("runnable image"));
        new ApplicationBuildResult("demo/app:1", "sha256:" + "1".repeat(64),
                "image", new JvmConfig()).save(mojo.project);
        assertTrue(assertThrows(org.apache.maven.plugin.MojoExecutionException.class,
                mojo::execute).getMessage().contains("no registry host"));
    }

    @Test
    void dryRunAndInvalidProbePreserveExistingOutput(@TempDir Path dir) throws Exception {
        ManifestMojo mojo = mojo();
        mojo.outputDirectory = dir.toFile();
        Path output = dir.resolve("javaapplication.yaml");
        Files.writeString(output, "existing");
        mojo.dryRun = true;
        mojo.execute();
        assertEquals("existing", Files.readString(output));
        mojo.dryRun = false;
        set(mojo, "readinessPath", "invalid-relative-path");
        assertThrows(org.apache.maven.plugin.MojoExecutionException.class,
                mojo::execute);
        assertEquals("existing", Files.readString(output));
    }

    @Test
    void buildsAreIsolatedPerProject() throws Exception {
        ManifestMojo mojo = mojo();
        mojo.project = new MavenProject();
        assertThrows(org.apache.maven.plugin.MojoExecutionException.class, mojo::execute);
    }

    @Test
    void actualBuildFeedsManifestAndFailedRebuildInvalidatesIt(@TempDir Path dir) throws Exception {
        BuildMojo build = new BuildMojo();
        Path jar = dir.resolve("app.jar");
        Files.write(jar, TestApplications.zip(java.util.Map.of("META-INF/MANIFEST.MF",
                "Manifest-Version: 1.0\nMain-Class: app.Main\n\n"
                        .getBytes(java.nio.charset.StandardCharsets.UTF_8))));
        TestApplications.configure(build, jar, dir.resolve("output"), false);
        build.format = "image";
        TestApplications.set(build, "ociOutputDirectory", dir.resolve("oci").toFile());
        build.execute();
        String digest = AbstractBrewletMojo.MAPPER.readTree(dir.resolve("oci/index.json").toFile())
                .path("manifests").get(0).path("digest").asText();
        ManifestMojo manifest = mojo();
        manifest.project = build.project;
        manifest.outputDirectory = build.outputDirectory;
        manifest.execute();
        assertEquals("example.test/app@" + digest, manifest.resolveDeployImage());
        assertTrue(Files.readString(dir.resolve("output/javaapplication.yaml"))
                .contains("\"example.test/app@" + digest + "\""));
        build.entryMode = "invalid";
        assertThrows(org.apache.maven.plugin.MojoExecutionException.class, build::execute);
        assertThrows(org.apache.maven.plugin.MojoExecutionException.class, manifest::execute);
    }

    private static void assertNoInferredProbes(String yaml) {
        assertFalse(yaml.contains("  probes:"), "ports do not declare a health contract");
        assertFalse(yaml.contains("httpGet:"));
        assertFalse(yaml.contains("liveness:"));
        assertFalse(yaml.contains("readiness:"));
    }

    private static ManifestMojo mojo() throws ReflectiveOperationException {
        ManifestMojo mojo = new ManifestMojo();
        mojo.project = new MavenProject();
        mojo.project.setVersion("1.0");
        mojo.jdkFeature = 17;
        new ApplicationBuildResult("registry.example.com/app:1", "sha256:" + "1".repeat(64),
                "image", new JvmConfig()).save(mojo.project);
        set(mojo, "appName", "orders");
        set(mojo, "namespace", "default");
        set(mojo, "replicas", 1);
        set(mojo, "cpuRequest", "500m");
        set(mojo, "memoryRequest", "256Mi");
        set(mojo, "cpuLimit", "2");
        set(mojo, "memoryLimit", "512Mi");
        return mojo;
    }

    private static void set(ManifestMojo mojo, String name, Object value)
            throws ReflectiveOperationException {
        Field field = ManifestMojo.class.getDeclaredField(name);
        field.setAccessible(true);
        field.set(mojo, value);
    }

    private static String render(ManifestMojo mojo, JvmConfig config) throws IOException,
            org.apache.maven.plugin.MojoExecutionException {
        StringWriter result = new StringWriter();
        mojo.writeJavaApplicationYaml(new PrintWriter(result), config);
        return result.toString();
    }

    private static List<String> scalars(String yaml, String prefix) throws IOException {
        List<String> values = new ArrayList<>();
        for (String line : yaml.lines().toList()) {
            if (line.startsWith(prefix)) {
                // Emitted scalars use the common JSON/YAML quoted-string grammar.
                values.add(AbstractBrewletMojo.MAPPER.readValue(
                        line.substring(prefix.length()), String.class));
            }
        }
        return values;
    }

    private static String controlsAndUnicodeLineBreaks() {
        StringBuilder value = new StringBuilder();
        for (char c = 0; c < 0x20; c++) {
            value.append(c);
        }
        for (char c = 0x7f; c <= 0x9f; c++) {
            value.append(c);
        }
        return value.append('\u2028').append('\u2029').toString();
    }
}
