// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by hand to satisfy runtime.Object (no controller-gen in this
// PoC module). Keep in sync with javaapplication_types.go.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *ArtifactSpec) DeepCopyInto(out *ArtifactSpec) {
	*out = *in
	if in.PullSecrets != nil {
		out.PullSecrets = make([]string, len(in.PullSecrets))
		copy(out.PullSecrets, in.PullSecrets)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ArtifactSpec) DeepCopy() *ArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *CDSSpec) DeepCopyInto(out *CDSSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *CDSSpec) DeepCopy() *CDSSpec {
	if in == nil {
		return nil
	}
	out := new(CDSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *JVMSpec) DeepCopyInto(out *JVMSpec) {
	*out = *in
	if in.Args != nil {
		out.Args = make([]string, len(in.Args))
		copy(out.Args, in.Args)
	}
	out.CDS = in.CDS
}

// DeepCopy returns a deep copy of the receiver.
func (in *JVMSpec) DeepCopy() *JVMSpec {
	if in == nil {
		return nil
	}
	out := new(JVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Enabled != nil {
		out.Enabled = new(bool)
		*out.Enabled = *in.Enabled
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ProbesSpec) DeepCopyInto(out *ProbesSpec) {
	*out = *in
	if in.Readiness != nil {
		out.Readiness = new(corev1.Probe)
		in.Readiness.DeepCopyInto(out.Readiness)
	}
	if in.Liveness != nil {
		out.Liveness = new(corev1.Probe)
		in.Liveness.DeepCopyInto(out.Liveness)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ProbesSpec) DeepCopy() *ProbesSpec {
	if in == nil {
		return nil
	}
	out := new(ProbesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		out.MinReplicas = new(int32)
		*out.MinReplicas = *in.MinReplicas
	}
	if in.TargetCPUUtilizationPercentage != nil {
		out.TargetCPUUtilizationPercentage = new(int32)
		*out.TargetCPUUtilizationPercentage = *in.TargetCPUUtilizationPercentage
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *JavaApplicationSpec) DeepCopyInto(out *JavaApplicationSpec) {
	*out = *in
	in.Artifact.DeepCopyInto(&out.Artifact)
	if in.Replicas != nil {
		out.Replicas = new(int32)
		*out.Replicas = *in.Replicas
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.JVM.DeepCopyInto(&out.JVM)
	if in.Env != nil {
		out.Env = make([]corev1.EnvVar, len(in.Env))
		for i := range in.Env {
			in.Env[i].DeepCopyInto(&out.Env[i])
		}
	}
	if in.Ports != nil {
		out.Ports = make([]corev1.ContainerPort, len(in.Ports))
		copy(out.Ports, in.Ports)
	}
	in.Service.DeepCopyInto(&out.Service)
	in.Probes.DeepCopyInto(&out.Probes)
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
	if in.Arch != nil {
		out.Arch = make([]string, len(in.Arch))
		copy(out.Arch, in.Arch)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *JavaApplicationSpec) DeepCopy() *JavaApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(JavaApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *JavaApplicationStatus) DeepCopyInto(out *JavaApplicationStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *JavaApplicationStatus) DeepCopy() *JavaApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(JavaApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *JavaApplication) DeepCopyInto(out *JavaApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *JavaApplication) DeepCopy() *JavaApplication {
	if in == nil {
		return nil
	}
	out := new(JavaApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *JavaApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *JavaApplicationList) DeepCopyInto(out *JavaApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]JavaApplication, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *JavaApplicationList) DeepCopy() *JavaApplicationList {
	if in == nil {
		return nil
	}
	out := new(JavaApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of the receiver.
func (in *JavaApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
