# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "brewlet.namespace" . }}
  labels:
    {{- include "brewlet.labels" . | nindent 4 }}
